tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.crt
      keyFile: /etc/traefik/certs/cert.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    redirect-https:
      rule: "HostRegexp(`{host:.+}`)"
      entrypoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://192.168.0.1"
